### ISSUE TITLE
BUG: Binary file (standard input) matches

### ISSUE THREAD

**Issue by starnakin** [LucasKuhn/minishell_tester#15]
When a use the tester on my minishell all exit code of my minishell equal Binary file (standard input) matches
![image](https://user-images.githubusercontent.com/47717174/229159524-1a67068b-b8bd-4030-8c22-2b0b047afab7.png)
except that all work perfectly 
![My minishell](https://git.chauvet.pro/starnakin/42_minishell)

**Comment by LucasKuhn** [comment]
Would you mind sharing your repo so I can test it? 
With only the image I can't reproduce it to check what's wrong

**Comment by starnakin** [comment]
sorry I have forgotten https://git.chauvet.pro/starnakin/42_minishell

**Comment by LucasKuhn** [comment]
I wasn't able to run your project, got this after calling make:
<img width="1067" alt="Screenshot 2023-03-31 at 4 13 54 PM" src="https://user-images.githubusercontent.com/26127185/229209328-a395c019-1f00-455d-b12a-25e7d080a406.png">
