### ISSUE TITLE
falta um teste basico nas builtins, cd sem argumentos

### ISSUE THREAD

**Issue by Vinni-Cedraz** [LucasKuhn/minishell_tester#17]
O tester esta me aprovando 100% nas builtins sendo que o cd sem argumentos da segfault:
![image](https://github.com/LucasKuhn/minishell_tester/assets/92558763/775b8a55-a2b2-4fb1-8a44-278c2bbc4acd)

**Comment by sgkhusal** [comment]
Olá, Vinícius!
O cd sem argumentos não faz parte do mandatório, o pdf pede para implementar o cd apenas com caminho absoluto ou relativo:
<img width="389" alt="image" src="https://github.com/LucasKuhn/minishell_tester/assets/75377067/eef8f5f2-084b-4c48-9f46-ed79b35c7bc3">

Por isso não colocamos ele nos testes mandatórios, assim como o `cd ~`
Nossa interpretação é de que o comportamento não precisa ser o mesmo do bash, e importante seria não ter comportamentos inesperados.
Atualmente esse teste está no arquivo `manual_tests/not_mandatory` junto com outros testes. Recomendo dar uma olhada nos outros arquivos dessa pasta, pois eles contém testes de partes obrigatórias, mas que são testados manualmente.

**Comment by Vinni-Cedraz** [comment]
Obrigado.

**Comment by Vinni-Cedraz** [comment]
Pra ficar consistente com essa logica, precisa tirar isso aqui do minishell_tester/manual tests/mandatory:

```
# Empty `cd` moves to home
cd
```

**Comment by LucasKuhn** [comment]
> Pra ficar consistente com essa logica, precisa tirar isso aqui do minishell_tester/manual tests/mandatory:
> 
> 
> 
> ```
> 
> # Empty `cd` moves to home
> 
> cd
> 
> ```

Essa issue aqui tá fechada já, mas fique a vontade pra fazer uma PR 😉
