### ISSUE TITLE
Basic test failed

### ISSUE THREAD

**Issue by Rel09** [LucasKuhn/minishell_tester#18]
Should test relative path like 
"/bin/ls"

**Comment by LucasKuhn** [comment]
Care to explain what exactly is breaking? 🙂

If you mean this specific test is not present, we added a hint that something like this should be tested manually:
https://github.com/LucasKuhn/minishell_tester/blob/65b466b21132ead249fced092f633ea16700a77b/manual_tests/mandatory#L29-L33

As referenced in the Manual Tests part of the readme: 
https://github.com/LucasKuhn/minishell_tester#manual-tests

**Comment by Rel09** [comment]
my bad, thanks for pointing it out !

**Comment by LucasKuhn** [comment]
No worries, good luck with the project 😉
