### ISSUE TITLE
exit code "wildcard" on test redirect n. 75

### ISSUE THREAD

**Issue by 552020** [LucasKuhn/minishell_tester#22]
I'm getting this strange exit code consistently on different machines. I suppose that this has to do with the fact that in the minishell_tester folder has a file names `wildcards` and we are testing a prompt which ends with the `ls` command. 

<img width="294" alt="image" src="https://github.com/LucasKuhn/minishell_tester/assets/60273337/643214c3-9916-4810-a981-f6194122c0b2">

**Comment by LucasKuhn** [comment]
Do you mind sharing your minishell so I can test this? Can't check without knowing exactly what you are running

**Comment by 552020** [comment]
Sure, this is our repo: https://github.com/552020/minishell but we don't get this issue anymore. To reproduce the issue you can checkout the commit 6ebae65. I tested it now and the issue is correctly reproduced. We passed minishell yesterday, your tester helped a lot! Thanks again. <3

**Comment by LucasKuhn** [comment]
Glad to hear, well done in your project! 🥳
Closing this for now ☺️
